### ISSUE TITLE
NixOS build: libcurl segfault

### ISSUE THREAD

**Issue by akru** [alexcrichton/cargo-vendor#222] opened 2019-03-07 15:18 UTC
According to https://github.com/NixOS/nixpkgs/pull/57017 when building `cargo-vendor` for NixOS.

**The problem**: `cargo vendor` command randomly spawn segfault in `libcurl` or sometime in `libc`.

**Reproduce steps**: 
```
git clone https://github.com/akru/nixpkgs -b cargo-vendor-update && cd nixpkgs
nix-build -I nixpkgs=. -A parity.cargoDeps --check
```

**Comment by akru** [comment] 2019-03-07 15:18
@alexcrichton Could you help me, where the problem is could be?

**Comment by andir** [comment] 2019-03-07 15:22
A backtrace for the segfault looks like this:

```
#0  0x00007ffff7f93ad1 in h2_pri_spec () from /nix/store/z1hlaaq623sl3iif64jwckwickfgzn15-curl-7.64.0/lib/libcurl.so.4
#1  0x00007ffff7f93b7f in h2_session_send () from /nix/store/z1hlaaq623sl3iif64jwckwickfgzn15-curl-7.64.0/lib/libcurl.so.4
#2  0x00007ffff7f943ba in h2_process_pending_input () from /nix/store/z1hlaaq623sl3iif64jwckwickfgzn15-curl-7.64.0/lib/libcurl.so.4
#3  0x00007ffff7f95678 in http2_conncheck () from /nix/store/z1hlaaq623sl3iif64jwckwickfgzn15-curl-7.64.0/lib/libcurl.so.4
#4  0x00007ffff7f62677 in extract_if_dead () from /nix/store/z1hlaaq623sl3iif64jwckwickfgzn15-curl-7.64.0/lib/libcurl.so.4
#5  0x00007ffff7f66520 in Curl_connect () from /nix/store/z1hlaaq623sl3iif64jwckwickfgzn15-curl-7.64.0/lib/libcurl.so.4
#6  0x00007ffff7f780c7 in multi_runsingle () from /nix/store/z1hlaaq623sl3iif64jwckwickfgzn15-curl-7.64.0/lib/libcurl.so.4
#7  0x00007ffff7f793b3 in curl_multi_perform () from /nix/store/z1hlaaq623sl3iif64jwckwickfgzn15-curl-7.64.0/lib/libcurl.so.4
#8  0x0000555555965d87 in curl::multi::Multi::perform ()
#9  0x0000555555739815 in cargo::core::package::Downloads::wait ()
#10 0x00005555555b423f in cargo::core::package::PackageSet::get_many ()
#11 0x00005555555c200a in cargo_vendor::sync ()
#12 0x00005555555bf8c6 in cargo_vendor::real_main ()
#13 0x00005555555bd00a in cargo_vendor::main ()
#14 0x00005555555a3df3 in std::rt::lang_start::{{closure}} ()
#15 0x00005555559722b3 in std::panicking::try::do_call ()
#16 0x000055555599134a in __rust_maybe_catch_panic ()
#17 0x0000555555981bfb in std::rt::lang_start_internal ()
#18 0x00005555555d7c35 in main ()
```

**Comment by andir** [comment] 2019-03-07 20:25
I downgraded to curl 7.63.0 and the segfaults are gone :/

**Comment by alexcrichton** [comment] 2019-03-08 14:43
This looks like it's possibly a bug in libcurl, the curl crate, or Cargo, although it's probably not a bug in cargo-vendor. Sorry I don't recognize the segfaults here and I wouldn't know how to debug this.

**Comment by sanmai-NL** [comment] 2019-03-31 12:57
@andir: Could you close this issue?

**Closed** 2019-03-31 19:21 UTC
