### ISSUE TITLE
Can this be use to easily temporarily override just one dependency and fix it,

### ISSUE THREAD

**Issue by vi** [alexcrichton/cargo-vendor#2] opened 2016-05-04 23:30 UTC
reverting to usual configuration after the fix goes upstream?

"Easily" means avoiding manually looking for the repository, checking it out, editing `Cargo.toml` to point to it and back.

**Comment by alexcrichton** [comment] 2016-05-05 16:16
Unofrutnately, no, that's what `paths` overrides in Cargo are currently intended for, however.

**Comment by vi** [comment] 2016-05-05 23:19
I though cargo-vendor can configure a `paths` override automatically, without thinking where to place the override.

Is there some other project for this purpose? I expected UX like this: `cargo override openssl`, edit `./overrides/openssl/...rs`, `cargo run`, `cargo unoverride openssl`.

**Comment by alexcrichton** [comment] 2016-05-06 16:01
Unfortunately no, there's not a subcommand for this

**Comment by conikeec** [comment] 2016-08-03 21:16
Failed to build with nightly 


Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading url v1.2.0
   Compiling strsim v0.3.0
   Compiling lazy_static v0.2.1
   Compiling winapi-build v0.1.1
   Compiling bitflags v0.1.1
   Compiling libc v0.2.14
   Compiling regex-syntax v0.3.4
   Compiling kernel32-sys v0.2.2
   Compiling advapi32-sys v0.1.2
   Compiling matches v0.1.2
   Compiling glob v0.2.11
   Compiling log v0.3.6
   Compiling memchr v0.1.11
   Compiling xattr v0.1.8
   Compiling aho-corasick v0.5.2
   Compiling rand v0.3.14
   Compiling num_cpus v0.2.13
   Compiling pkg-config v0.3.8
   Compiling winapi v0.2.8
   Compiling crossbeam v0.2.9
   Compiling openssl-sys v0.7.14
   Compiling tempdir v0.3.5
   Compiling unicode-normalization v0.1.2
   Compiling gcc v0.3.32
   Compiling nom v1.2.4
   Compiling utf8-ranges v0.1.3
   Compiling unicode-bidi v0.2.3
   Compiling semver v0.2.3
   Compiling cmake v0.1.17
   Compiling miniz-sys v0.1.7
   Compiling libz-sys v1.0.5
   Compiling curl-sys v0.1.34
   Compiling libssh2-sys v0.1.37
   Compiling libgit2-sys v0.4.4
   Compiling idna v0.1.0
   Compiling fs2 v0.2.5
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.6
   Compiling term v0.4.4
   Compiling regex v0.1.73
   Compiling flate2 v0.2.14
   Compiling filetime v0.1.10
   Compiling url v1.2.0
   Compiling tar v0.4.7
   Compiling rustc-serialize v0.3.19
   Compiling curl v0.2.19
   Compiling git2 v0.4.4
   Compiling uuid v0.1.18
   Compiling toml v0.1.30
   Compiling url v0.2.38
   Compiling env_logger v0.3.4
   Compiling docopt v0.6.82
   Compiling crates-io v0.2.0
   Compiling git2-curl v0.4.1
   Compiling cargo v0.11.0
   Compiling cargo-vendor v0.1.1
error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/cargo_vendor.0.o" "-o" "/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/cargo_vendor" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps" "-L" "/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/build/libgit2-sys-b2a68819b9a94017/out/lib" "-L" "/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/build/libssh2-sys-c4765b00ae89bf13/out/lib" "-L" "/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/build/miniz-sys-60c8d67696f63a43/out" "-L" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libcargo-9f39e6dcf6f02c39.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libtoml-1a75b37a708f335b.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libtempdir-c5a9975021308003.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libtar-10e5f62353d41d19.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libxattr-16bf42e901af78bf.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libsemver-60d1aa0e68346373.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libnum_cpus-9256729e2e3ab66d.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libglob-028bcc81f721b7f5.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libgit2-dbe5af82826f4a0e.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/liblibgit2_sys-4240891edcea7aa6.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libbitflags-fdf4b7654a6da3e5.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libflate2-d719035eaa7c6a88.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libminiz_sys-722889de4af2439c.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libfiletime-7100ae4a7fd471a6.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libcrossbeam-95e5cb210400af41.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libcrates_io-2bcb266090a2cbcd.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/liburl-7ed3313cfb59977c.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libuuid-13c4decae1c5ee4b.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/librand-49a08859d086fffe.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libcurl-0286b44e1d98c1ee.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libcurl_sys-55642974de419d95.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/liblog-bf16bb9a4912b11d.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libfs2-8e6e3f430ae191f6.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libdocopt-c2a0ac91deaa6c56.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/librustc_serialize-3561541d79c18212.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libregex-a1c323daba09617d.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libutf8_ranges-5c6a6dacba3be7ce.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libregex_syntax-b24da02611351433.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libaho_corasick-e528bf4fdf3954ff.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libmemchr-c555f740a543880f.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/liblazy_static-359f5533c970cd71.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/liblibssh2_sys-dc06faa4916a7285.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libopenssl_sys-1fd52a993b3834a7.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/liblibz_sys-4c0b4a70ced04023.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libnom-24d7a34b1cbfee73.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/liburl-d2e26827701e4972.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libidna-82ebdb343d6c1855.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libunicode_bidi-04ad1da5552425fd.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libmatches-5d5580ffd528031c.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libthread_local-e5ce0d44bcaf00e6.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libthread_id-bcd46c79a620a618.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/liblibc-1f3392fe1afd1313.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libterm-44dfa57762d62876.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libunicode_normalization-5de3a9c8fd8ddf4e.rlib" "/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH/release/deps/libstrsim-6c9aaf530d99b06b.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librand-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcollections-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_jemalloc-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_unicode-c8005792.rlib" "/Users/chetanconikee/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-c8005792.rlib" "-l" "iconv" "-framework" "Security" "-framework" "CoreFoundation" "-l" "curl" "-l" "ssl" "-l" "crypto" "-l" "z" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m" "-l" "compiler-rt"
note: Undefined symbols for architecture x86_64:
  "_EVP_aes_256_ctr", referenced from:
      _libssh2_crypt_method_aes256_ctr in liblibssh2_sys-dc06faa4916a7285.rlib(crypt.c.o)
     (maybe you meant: __libssh2_EVP_aes_256_ctr)
  "_libiconv", referenced from:
      _git_path_iconv in liblibgit2_sys-4240891edcea7aa6.rlib(path.c.o)
  "_EVP_aes_192_ctr", referenced from:
      _libssh2_crypt_method_aes192_ctr in liblibssh2_sys-dc06faa4916a7285.rlib(crypt.c.o)
     (maybe you meant: __libssh2_EVP_aes_192_ctr)
  "_EVP_aes_128_ctr", referenced from:
      _libssh2_crypt_method_aes128_ctr in liblibssh2_sys-dc06faa4916a7285.rlib(crypt.c.o)
     (maybe you meant: __libssh2_EVP_aes_128_ctr)
  "_libiconv_open", referenced from:
      _git_path_direach in liblibgit2_sys-4240891edcea7aa6.rlib(path.c.o)
      _git_path_iconv_init_precompose in liblibgit2_sys-4240891edcea7aa6.rlib(path.c.o)
      _git_path_diriter_init in liblibgit2_sys-4240891edcea7aa6.rlib(path.c.o)
  "_libiconv_close", referenced from:
      _git_path_direach in liblibgit2_sys-4240891edcea7aa6.rlib(path.c.o)
      _git_path_iconv_clear in liblibgit2_sys-4240891edcea7aa6.rlib(path.c.o)
      _git_path_diriter_free in liblibgit2_sys-4240891edcea7aa6.rlib(path.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error
error: failed to compile `cargo-vendor v0.1.1`, intermediate artifacts can be found at `/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/cargo-install.ZZu42HxRx0yH`

Caused by:
  Could not compile `cargo-vendor`.

To learn more, run the command again with --verbose.

**Comment by alexcrichton** [comment] 2017-03-07 16:00
I'm going to close this as I don't believe this is the intended use case of this command.

**Closed by alexcrichton** 2017-03-07 16:00 UTC
