### ISSUE TITLE
Hash checking conflicts with git file mangling

### ISSUE THREAD

**Issue by jsgf** [alexcrichton/cargo-vendor#13] opened 2016-11-09 11:00 UTC
I'm trying to use cargo-vendor to download all the dependencies for a crate, then commit the crate source + dependencies into git as a single repo.

Git uses a `.gitattributes` file to allow you to match patterns and set file types - in particular, how to treat line endings.

If a vendored source base has a `.gitattributes` that changes the line endings (for example, unix-style endings for MSVC proj files), then git will apply those endings to the files when they're checked out. This causes cargo's hash check to fail, because cargo-vendor computes the hash on the original, unmodified file content.

This can't be fixed by putting a `.gitattributes` in the top-level repo of the directory, because the `.gitattributes` that's closer to the files in question (ie, in the vendored source), take precedence.

I'm not really sure how to fix this. The options I can think of are:

1. remove .gitattribute files on import
2. apply git attributes before computing hash (but that only works if the source is ultimately going to be stored in git)
3. exclude files that match .gitattributes from hash computation
4. include multiple hashes for each transformation
5. normalize files when computing + checking hashes
6. option to disable hash checking
7. ...?

Option 6 seems like the simplest and quickest for now...

**Comment by jsgf** [comment] 2016-11-09 12:24
I went with running a script to recompute the hashes before calling `cargo build`. Not very pretty, but it works for now.

**Comment by alexcrichton** [comment] 2016-11-09 16:23
Oh so to clarify, the problem is for projects with a published `.gitattributes` file? This utility definitely shouldn't include that and it should be easy to filter out. In general though, yeah, we intended that the vendor directory would be checked in to configure git to not touch the files (aka treat them as binary) so the line endings wouldn't get modified.

If the problem though is upstream projects having an internal `.gitattributes` that's changing how they're checked out we should definitely remove them.

**Comment by jsgf** [comment] 2016-11-09 20:04
Yeah, excluding `.gitattributes` would generally work except that git's default is "auto" conversion, which might still try to do windows<->unix eol conversion.

Also `libgit2` (included in the source of the `libgit2-sys` crate) has a pile of `.gitattributes` which are part of its test suite rather than actual ones, but  we can probably let that slide.

**Closed** 2016-11-10 02:49 UTC
